# modules/__init__.py
# Intencionalmente vacío para evitar side-effects de import.
# Importá submódulos explícitamente desde app.py:
#   from modules.auth import ...
#   from modules.ui import ...
#   from modules.drive import ...
#   from modules.gsc import ...
#   from modules.analysis import ...
#   from modules.utils import ...
